; -----------------------------------------------------------------------------
; Architectural module: 00_definitions.asm
; Platform constants, tagged cells, workspace symbols, and frame layout.
; Original monolithic line range: 1-375.
; Emitted address range: no emitted bytes.
; -----------------------------------------------------------------------------

; micro-PROLOG resurrection source — v025 second-review improvement baseline
; Original disassembly generated by z80dasm 1.1.3
; command line: z80dasm -a -t -l -g 24576 -b blocks.txt prolog.bin

; ROM routines

; ============================================================================
; CHAPTER 0 — THE MACHINE THAT THE REST OF THE SOURCE ASSUMES
; ============================================================================
;
; A disassembler sees addresses and instructions.  The interpreter sees a much
; smaller, tidier machine of its own invention: three-byte terms, six-byte heap
; objects, twelve-byte execution records, and a handful of fixed workspace
; words which act like registers for that virtual machine.
;
; This file gives names to that invented machine.  It emits no bytes.  Reading
; it first is worthwhile because nearly every short sequence later in the
; source is manipulating one of the layouts declared here.  In particular,
; remember these three scales:
;
;       3 bytes   one tagged term cell
;       6 bytes   one managed heap object or trail node
;      12 bytes   one execution frame / choice-point snapshot
;
; The Z80 registers are only temporary couriers.  The durable interpreter state
; lives in the fixed words beginning at 0x9800, named below.
;
; The interpreter deliberately delegates hardware-facing work to the Spectrum
; ROM.  ROM routines are treated as an imported machine substrate: keyboard
; scanning, screen channels, cursor handling, graphics primitives, sound, and
; cassette pulse timing remain ROM responsibilities.  Everything above that
; boundary--terms, clauses, unification, modules, and the supervisor--belongs to
; micro-PROLOG itself.  A reader can therefore treat the ROM symbols below like
; an operating-system API rather than unexplained pieces of the interpreter.
ROM_LD_EDGE_1:                 equ 005e7h
ROM_LD_EDGE_2:                 equ 005e3h
ROM_OUT_CURS_WITHOUT_CHECK:    equ 018e8h
ROM_INPUT_AD:                  equ 015e6h
ROM_PRINT_A_2:                 equ 015f2h

; system variables

SYSVAR_ERR_SP:                 equ 05c3dh   ; Address of item on machine stack to use as error return
SYSVAR_CHANS:                  equ 05c4fh   ; Address of channel data
SYSVAR_CURCHL:                 equ 05c51h   ; Address of information used for input and output
SYSVAR_SCR_CT:                 equ 05c8ch   ; Scroll counter
SYSVAR_ATTR_T:                 equ 05c8fh   ; Temporary current colours
SYSVAR_ATTR_P:                 equ 05c8dh   ; Permanent current colours
SYSVAR_COORDS:                 equ 05c7dh   ; Coordinates of last point plotted
SYSVAR_MODE:                   equ 05c41h   ; Specifies K, L, C, E or G cursor
SYSVAR_S_POSNL2:               equ 05c8bh   ; Like S-POSN for lower part of screen 
SYSVAR_DF_SZ:                  equ 05c6bh   ; The number of lines in the lower part of the screen
SYSVAR_BORDCR:                 equ 05c48h   ; Border colour
SYSVAR_SEED:                   equ 05c76h   ; The seed for RND
SYSVAR_FRAMES:                 equ 05c78h   ; Frame counter
SYSVAR_P_FLAG:                 equ 05c91h   ; More flags

; -----------------------------------------------------------------------------
; Tagged term representation
; -----------------------------------------------------------------------------
; Most runtime terms occupy one three-byte cell:
;
;   +0  tag
;   +1  payload low byte
;   +2  payload high byte
;
; Some tags interpret the payload as a value, others as an absolute or relative
; pointer.  Names remain conservative where the exact semantic distinction is
; not yet proved.

TERM_CELL_SIZE:                    equ 003h
FLOAT_VALUE_SIZE:                  equ 006h

; ----------------------------------------------------------------------------
; THE TERM LANGUAGE
; ----------------------------------------------------------------------------
;
; Every Prolog value begins with a tag byte and normally carries a 16-bit
; payload.  A cell is therefore small enough to copy cheaply yet rich enough to
; describe atoms, integers, lists and several kinds of reference.
;
; The reference tags are the subtle part.  A relative reference names a fresh
; variable in a clause environment; an absolute reference names a cell
; directly; REFERENCE_NEXT_CELL points at the second half of a six-byte object
; without publishing an interior heap address to the collector.  The unifier
; follows all three until it reaches an actual value or an unbound variable.
;
; Bit 7 is not another type.  The collector borrows it temporarily as a mark
; bit, then clears it during sweep.  Code which asks what a term *is* must mask
; that bit when collection may have marked the object.
;
; Reference tags: one variable through its lifetime
; -------------------------------------------------
; A variable begins as an unbound three-byte cell:
;
;       address V:   [ UNBOUND | unused word ]
;
; It can later become one of three references:
;
;   ABSOLUTE_REFERENCE  [ 01 | address T ]
;       Follow T directly.  This is the ordinary binding form.
;
;   REFERENCE_NEXT_CELL [ 05 | address of this cell ] [ value cell follows ]
;       Follow the adjacent cell.  The representation is useful when a binding
;       and its copied value are allocated as one six-byte object.
;
;   RELATIVE_REFERENCE [ 0C | byte offset N ]
;       Add N to the current clause-local environment base.  Compiled clauses
;       use this form so the same stored clause can receive fresh variables on
;       every invocation.
;
; Example: binding X to integer 7 normally changes only X:
;
;       before: X = [ 00 | ---- ]
;       value:      [ 04 | 0007 ]
;       after:  X = [ 01 | &value ]
;
; Dereferencing repeatedly follows these forms until it reaches a concrete term
; or an unbound variable.  The complete executable walk appears in module 02 at
; term_dereference_hl.
; ----------------------------------------------------------------------------
; COMPLETE LIFE OF ONE LOGICAL VARIABLE
; ----------------------------------------------------------------------------
;
; The same source variable changes representation as it moves through the
; interpreter.  The following trace is the reference example used by the
; executor and unifier chapters.
;
; Source clause:
;
;       ((P X) (Q X))
;
; Stored clause (read-only):
;
;       head X = [ RELATIVE_REFERENCE | 0000 ]
;       body X = [ RELATIVE_REFERENCE | 0000 ]
;
; `0000` means "the first local cell of this invocation".  On clause entry the
; selector allocates a fresh environment base E and initializes:
;
;       E+0 = [ UNBOUND_VARIABLE | ---- ]
;
; Dereferencing either stored X adds the relative offset to E and reaches the
; same local cell.  If unification binds X to integer 7, the local becomes:
;
;       E+0 = [ ABSOLUTE_REFERENCE | address(integer_7) ]
;
; If X was allocated before the current choice point, the binding also creates
; a six-byte trail node:
;
;       [ target = E+0 ] [ previous = old_trail_head ]
;
; On failure, rollback follows that node and restores only the tag:
;
;       E+0 = [ UNBOUND_VARIABLE | payload ignored ]
;
; A REFERENCE_NEXT_CELL binding follows the same lifetime.  It is used when the
; bound value is the adjacent second cell of a six-byte heap object; rollback
; recovers that adjacent address before clearing its tag.  Thus RELATIVE is the
; compiled-clause form, ABSOLUTE/NEXT_CELL are runtime binding forms, and
; UNBOUND is the state restored by backtracking.
TERM_TAG_UNBOUND_VARIABLE:         equ 000h
TERM_TAG_ABSOLUTE_REFERENCE:       equ 001h
TERM_TAG_LIST:                     equ 003h
TERM_TAG_INTEGER:                  equ 004h
TERM_TAG_REFERENCE_NEXT_CELL:      equ 005h
TERM_TAG_CONSTANT:                 equ 008h
TERM_TAG_FLOAT:                    equ 00ah
TERM_TAG_RELATIVE_REFERENCE:       equ 00ch
TERM_TAG_END:                      equ 010h
TERM_TAG_MODULE:                   equ 007h
TERM_MARK_BIT_INDEX:               equ 007h

; During unification B is a two-bit provenance mask.  A set bit means the
; corresponding operand was reached by following at least one encoded
; reference.  This affects whether a value can be copied directly or must be
; normalized away from its source environment before a variable is bound.
; The word "provenance" below means only how the operand was reached.  A set bit
; says "dereferencing crossed at least one reference cell, so the resolved term
; may belong to a temporary environment".  These are not truth flags, success
; flags, or extra term-type bits.
UNIFY_LEFT_WAS_REFERENCED_BIT:      equ 000h
UNIFY_RIGHT_WAS_REFERENCED_BIT:     equ 001h

; Trail nodes are ordinary two-cell allocations used in a special context.
; The first cell names the variable whose tag was overwritten; the second cell
; is a LIST link to the previous trail head.  The 0x0C tag is reused here as a
; GC-visible marker for a fixed execution-arena address, not as an environment
; offset.  Heap variables use normal absolute or next-cell references.
; Why a trail exists
; ------------------
; Prolog may bind an old variable and later discover that the chosen clause
; fails.  Rewinding heap and frame cursors removes young allocations, but an old
; variable cell remains in place and must be restored explicitly.  The trail is
; a linked undo log of exactly those old cells.
;
; Pseudocode for backtracking is:
;
;       while trail_head != saved_trail_boundary:
;           variable = trail_head.target
;           variable.tag = UNBOUND
;           trail_head = trail_head.previous
;
; Choice points, the age test, and the exact untrail routine are introduced in
; modules 01 and 02.  At this point only the six-byte record layout is needed.
; In the trail discussion an "old" variable means one allocated before the
; current choice point.  Rewinding the allocation frontiers cannot remove such
; a cell, so it needs an explicit undo record.  A "young" variable was allocated
; after the choice point and disappears automatically when the frontier is
; restored.  The numeric age test is worked through in module 02.
TRAIL_NODE_SIZE:                    equ 006h
TRAIL_TARGET_CELL:                  equ 000h
TRAIL_PREVIOUS_CELL:                equ 003h
TRAIL_TARGET_EXECUTION_CELL:        equ TERM_TAG_RELATIVE_REFERENCE
TRAIL_TARGET_HEAP_CELL:             equ TERM_TAG_ABSOLUTE_REFERENCE
TRAIL_TARGET_HEAP_NEXT_CELL:        equ TERM_TAG_REFERENCE_NEXT_CELL

SYSTEM_NAME_TERMINATOR:            equ 0ffh
DISPATCH_REJECT:                   equ 0ffh

; Shared cells in the permanent supervisor term graph.  These aliases are used
; by the reconstructed CL and DELCL definitions without pretending that the
; neighbouring still-unconverted supervisor program is executable code.
; Permanent term-graph anchors
; ----------------------------
; These addresses name cells in the precompiled supervisor program stored later
; in the image.  They are analogous to labels for read-only AST nodes: module 10
; renders the surrounding graphs back into clauses such as EQ, OR, CL, and
; DELCL.  Keeping the aliases here lets earlier executable code refer to those
; immutable terms without forcing the reader to understand their full graph yet.
; Reading advice: do not decode the numeric addresses in the following aliases at
; this point.  Treat them as opaque read-only syntax-tree handles.  Module 10
; reconstructs every permanent graph symbolically and prints its source-level
; clause before showing the tagged cells which prove it.
STATIC_ARGS_V0_V1:                    equ 0847fh ; proper list (V0 V1)
STATIC_ARGS_V1:                       equ 08485h ; proper list (V1)
SUPERVISOR_EQ_VALUE_CELL:              equ 083f5h
SUPERVISOR_OR_VALUE_CELL:              equ 08467h
SUPERVISOR_ALL_VALUE_CELL:             equ 087b6h
STATIC_ARGS_V0:                       equ 088afh ; proper list (V0)

; Interpreter error numbers are passed to the built-in ?ERROR? relation when
; one is installed, otherwise the supervisor prints "Error:  n" and restarts.
; These values are defined by Appendix C of the reference manual.
ERROR_ARITHMETIC_OVERFLOW:         equ 000h
ERROR_ARITHMETIC_UNDERFLOW:        equ 001h
ERROR_NO_CLAUSES:                  equ 002h
ERROR_CONTROL:                     equ 003h
ERROR_ADD_CLAUSE:                  equ 004h
ERROR_FILE:                        equ 005h
ERROR_BREAK:                       equ 00bh
ERROR_ILLEGAL_MODULE_USE:          equ 00ch

; A system constant such as CON:, LST:, PUN: or RDR: points at a small
; descriptor beginning with tag 0x06.  Opened user files reuse the same tag but
; replace the 0xFFFF payload with a pointer to a mutable file-control block.
; The name is intentionally conservative: tag 0x06 may have uses beyond I/O.
SYSTEM_OBJECT_TAG:                 equ 006h
SYSTEM_OBJECT_NO_PAYLOAD:          equ 0ffffh

; I/O mode byte retained by W/WRITE/LISTP and consumed by the common printer.
IO_FORMAT_RAW:                     equ 000h ; P/W format: constants unquoted
IO_FORMAT_READABLE:                equ 001h ; PP/WRITE format: quoted, newline

; Three writable JP trampolines decouple the parser/printer from concrete
; devices.  Selecting CON:, the compatibility RDR: source, an opened file, or RFILL only replaces the
; target word following the JP opcode; the token and term code always calls the
; same stable addresses.
IO_INPUT_CALLBACK_JUMP:            equ 09865h
IO_UNREAD_CALLBACK_JUMP:           equ 09868h
IO_OUTPUT_CALLBACK_JUMP:           equ 0986bh
IO_FORMAT_MODE:                    equ 0986eh
PARSER_ERROR_STACK:                equ 09863h
IO_INPUT_CALLBACK_TARGET:          equ IO_INPUT_CALLBACK_JUMP+1
IO_UNREAD_CALLBACK_TARGET:         equ IO_UNREAD_CALLBACK_JUMP+1
IO_OUTPUT_CALLBACK_TARGET:         equ IO_OUTPUT_CALLBACK_JUMP+1

; Fixed runtime workspace outside the 14,200-byte interpreter image.  The
; cold-start initializer assigns the dynamic arena and dictionary partition;
; the remaining cells below have stable roles across parser, supervisor and
; device subsystems.
; Workspace orientation
; ---------------------
; The fixed workspace is the interpreter's set of global roots and scratch
; cells.  The dynamic region above it is a two-ended arena:
;
;       low addresses                                  high addresses
;       +------------------ free gap -------------------------------+
;       ^ execution frames grow upward       heap objects grow downward ^
;       EXECUTION_TOP                                 TERM_HEAP_CURSOR
;
; A name-pool partition sits below that arena and is managed by a bitmap.  Words
; named *_ROOT keep objects alive; words named *_CURSOR or *_TOP are allocation
; boundaries; callback targets are self-patched JP operands.  See
; analysis/MEMORY_MAP.md for the complete address map and module 12 for the cold
; start code that initializes these cells.
; ----------------------------------------------------------------------------
; WORKSPACE OWNERSHIP MAP
; ----------------------------------------------------------------------------
;
; Nearby addresses are not necessarily one data structure.  The fixed workspace
; is better read as four ownership bands:
;
;   protected native state
;       SUPERVISOR_MACHINE_STACK, ROM error return, saved callbacks
;
;   hot logical-machine state
;       EXEC_* words, current frame, choice point, trail and arena frontiers
;
;   parser / printer / primitive scratch
;       token buffer, variable maps, decimal workspaces, argument slots
;
;   device and persistent workspace state
;       current module dictionaries, file-control block, line-editor buffer
;
; Each later chapter names the subset it owns.  Physical adjacency here is a
; consequence of fitting the machine into RAM, not evidence of semantic unity.
SUPERVISOR_MACHINE_STACK:          equ 09803h
EXEC_ARENA_LIMIT:                  equ 09837h
PRIMITIVE_DISPATCH_SLOT_CURSOR:    equ 09861h
CONSOLE_COPY_TO_PRINTER:           equ 0996fh
LINE_EDITOR_CURSOR_LETTER:         equ 09970h
LINE_EDITOR_READ_INDEX:            equ 09971h
LINE_EDITOR_LENGTH:                equ 09972h
LINE_EDITOR_BUFFER:                equ 09973h
LINE_EDITOR_BUFFER_CAPACITY:       equ 0fah
TYPEAHEAD_COUNT:                   equ 09a73h
TYPEAHEAD_BUFFER:                  equ 09a74h
TYPEAHEAD_CAPACITY:                equ 010h
RDR_PUSHBACK_BYTE:                 equ 09a84h
DISPLAY_LAST_TEXT_ROW:             equ 09b6ch
DICTIONARY_NAME_POOL_START:        equ 09da5h

; Character-class bits returned by input_classify_character.  Several
; characters intentionally carry more than one bit: '-' can begin a negative
; number and also continue alphanumeric or graphic names; X/Y/Z/x/y/z are both
; letters and variable-prefix characters.
LEX_CLASS_ALPHANUMERIC:            equ 001h
LEX_CLASS_DIGIT:                   equ 002h
LEX_CLASS_STRUCTURAL:              equ 004h ; (, ), |
LEX_CLASS_GRAPHIC:                 equ 008h
LEX_CLASS_SINGLE_TOKEN:            equ 010h ; quote or one-character bracket
LEX_CLASS_SEPARATOR:               equ 020h
LEX_CLASS_VARIABLE_PREFIX:         equ 040h
LEX_CLASS_SIGN:                    equ 080h

TOKEN_KIND_GRAPHIC:                equ 002h
TOKEN_KIND_ALPHANUMERIC:           equ 003h
TOKEN_KIND_INTEGER:                equ TERM_TAG_INTEGER
TOKEN_KIND_QUOTED:                 equ 005h
TOKEN_KIND_SINGLE:                 equ TERM_TAG_CONSTANT
TOKEN_KIND_FLOAT:                  equ TERM_TAG_FLOAT

VARIABLE_PRINT_PREFIX_COUNT:       equ 006h ; X,Y,Z,x,y,z
VARIABLE_PRINT_OVERFLOW_CHAR:      equ 03fh ; '?'
VARIABLE_NAME_SPELLING_MAP:        equ 098efh

; One cassette file may be open at a time.  The mutable state byte lies at
; 0x9B96; the surrounding 0x134-byte record also contains an expected block
; identity, a byte cursor, a 256-byte physical transfer area, and the ten-byte
; identity footer stored on tape.  Only payload indexes 0..254 are used: 0xFF
; is reserved as the input-refill cursor, so the physical byte at index 255 is
; padding immediately before the footer.
; Only one cassette file can be open in this Spectrum build.  FILE_CONTROL_TABLE
; therefore names one 0x134-byte control block rather than an array of active
; files.  Module 12 explains its state, 255-byte payload convention, numbered
; block footer, refill path, EOF marker, and final partial-block flush.
FILE_CONTROL_TABLE:                equ 09b96h
FILE_CONTROL_BLOCK_COUNT:          equ 001h
FILE_CONTROL_BLOCK_STRIDE:         equ 0134h
FILE_CONTROL_STATE:                equ 000h
FILE_CONTROL_CURSOR:               equ 002h
FILE_CONTROL_DATA:                 equ 003h
FILE_CONTROL_EXPECTED_IDENTITY:    equ -024h ; eight-byte name + two ASCII digits
FILE_CONTROL_BLOCK_NUMBER:         equ -01ch ; relative to state, identity +8
FILE_CONTROL_TRANSFER_FOOTER:      equ 103h  ; state +3 + 0x100 physical bytes
FILE_CONTROL_FOOTER_BLOCK_NUMBER:  equ 10bh  ; footer +8
FILE_CONTROL_PHYSICAL_DATA_SIZE:   equ 100h
FILE_CONTROL_USABLE_DATA_SIZE:     equ 0ffh  ; indexes 0..0xFE
FILE_CONTROL_TAPE_RECORD_SIZE:     equ 10ah  ; 256 data bytes + 10-byte footer
FILE_CONTROL_NAME_SIZE:            equ 008h
FILE_CONTROL_IDENTITY_SIZE:        equ 00ah
FILE_CONTROL_UNUSED_FLAG:          equ 0fch ; cleared by OPEN/CREATE; exact role unknown

FILE_STATE_FREE:                   equ 000h
FILE_STATE_READING:                equ 001h
FILE_STATE_WRITING:                equ 002h
FILE_CURSOR_REFILL_REQUIRED:       equ 0ffh
FILE_BUFFER_EOF:                   equ 01ah

; Operation numbers understood by spectrum_io_dispatch.  The 0x1A operation
; merely selects the transfer buffer.  READ/WRITE transfer exactly 266 bytes:
; 256 physical payload bytes followed by an eight-character file name and a
; two-digit decimal block sequence.
DEVICE_OP_READER_INPUT:            equ 003h
DEVICE_OP_PUNCH_OUTPUT:            equ 004h
DEVICE_OP_PRINTER_OUTPUT:          equ 005h
DEVICE_OP_CONSOLE_IO:              equ 006h
DEVICE_OP_INIT_INPUT_IDENTITY:     equ 00fh
DEVICE_OP_READ_TAPE_BLOCK:         equ 014h
DEVICE_OP_WRITE_TAPE_BLOCK:        equ 015h
DEVICE_OP_INIT_OUTPUT_IDENTITY:    equ 016h
DEVICE_OP_SELECT_TRANSFER_BUFFER:  equ 01ah
FILE_TAPE_BLOCK_TYPE:              equ 0fbh

; Primitive-dispatch scratch slots.  Each six-byte slot retains both the
; resolved argument and enough information to bind an unbound output.
; ----------------------------------------------------------------------------
; PRIMITIVE ARGUMENT DISPATCH
; ----------------------------------------------------------------------------
;
; Native predicates do not each contain a hand-written argument parser.  They
; share a compact state machine.  Each five-byte state says where to go for a
; numeric term, a constant, another bound term, or an unbound variable; a zero
; transition means that combination is illegal.
;
; The dispatcher walks the call arguments, dereferences them, stores useful
; addresses in six-byte scratch slots, and advances through these relative
; transitions.  What looked in the original disassembly like tiny nonsensical
; instruction sequences is therefore data: a miniature bytecode describing the
; legal modes of a relation.
;
; ----------------------------------------------------------------------------
; ONE SIX-BYTE PRIMITIVE ARGUMENT SLOT
; ----------------------------------------------------------------------------
;
; The dispatcher uses one heap-object-sized slot for each argument:
;
;       +0  state/tag of the resolved input, or 0xFF when slot is unused
;       +1  original destination low byte
;       +2  original destination high byte
;       +3  resolved value / pending-result tag
;       +4  resolved value / pending-result payload low
;       +5  resolved value / pending-result payload high
;
; For an input, +3..+5 hold the dereferenced value seen by the handler.  For an
; unbound output, +1..+2 remember the variable which must eventually receive a
; value, while the handler writes its proposed result to +3..+5.  Results are
; committed only after the handler returns logical success.  The overlapping
; aliases below deliberately name the same bytes from these different phases.
PRIMITIVE_ARG1_SLOT:              equ 09807h
PRIMITIVE_ARG2_SLOT:              equ 0980dh
PRIMITIVE_ARG3_SLOT:              equ 09813h
PRIMITIVE_ARG4_SLOT:              equ 09819h

PRIMITIVE_ARG1_RESULT_TAG:        equ 09807h
PRIMITIVE_ARG1_RESULT_VALUE:      equ 09808h
PRIMITIVE_ARG1_VALUE:             equ 0980ah
PRIMITIVE_ARG1_TAG:               equ 0980ch
PRIMITIVE_ARG2_RESULT_TAG:        equ 0980dh
PRIMITIVE_ARG2_RESULT_VALUE:      equ 0980eh
PRIMITIVE_ARG2_VALUE:             equ 09810h
PRIMITIVE_ARG2_TAG:               equ 09812h
PRIMITIVE_ARG3_RESULT_TAG:        equ 09813h
PRIMITIVE_ARG3_RESULT_VALUE:      equ 09814h
PRIMITIVE_ARG3_VALUE:             equ 09816h
PRIMITIVE_ARG3_TAG:               equ 09818h
PRIMITIVE_ARG4_RESULT_TAG:        equ 09819h
PRIMITIVE_ARG4_RESULT_VALUE:      equ 0981ah
PRIMITIVE_ARG4_VALUE:             equ 0981ch
PRIMITIVE_ARG4_TAG:               equ 0981eh
PRIMITIVE_ARG5_VALUE:             equ 09822h
PRIMITIVE_ARG6_VALUE:             equ 09828h
ERROR_HANDLER_VALUE_CELL:         equ 09b1ah ; cached dictionary value for "?ERROR?"
CONSOLE_LAST_CHARACTER:            equ 09b69h
TAPE_TRANSFER_BUFFER_PTR:          equ 09b6ah
ACTIVE_FILE_CONTROL_BLOCK:         equ 09b6dh

; Arithmetic work areas.  The dispatcher converts each numeric argument into
; an eleven-byte sign/exponent/decimal-digit buffer before arithmetic.  Two
; larger scratch regions hold intermediate sums, products and quotients.
; The numeric workspaces are declared here only because this is the global memory
; map.  A first-time reader may skip their field details until module 11.  The
; important preview is that packed decimal digits are expanded to one digit per
; byte, with separate sign, exponent, carry and guard positions.
NUMERIC_WORK_A:                   equ 09b1fh
NUMERIC_WORK_A_EXPONENT:          equ NUMERIC_WORK_A+1
NUMERIC_WORK_A_FIRST_DIGIT:       equ NUMERIC_WORK_A+2
NUMERIC_WORK_A_LAST_DIGIT:        equ NUMERIC_WORK_A+10
NUMERIC_WORK_A_END:               equ NUMERIC_WORK_A+18
NUMERIC_WORK_B:                   equ 09b33h
NUMERIC_WORK_B_DIGIT_WINDOW:      equ NUMERIC_WORK_B+8
NUMERIC_ARG1_BUFFER:              equ 09b47h
NUMERIC_ARG2_BUFFER:              equ 09b52h
NUMERIC_ARG3_BUFFER:              equ 09b5dh

; Generic list-walker callback trampoline.  Address 0x9800 contains JP and the
; following word is changed by callers to select the element callback.
LIST_WALK_CALLBACK_JUMP:            equ 09800h
LIST_WALK_CALLBACK_TARGET:          equ 09801h

; Module and dictionary workspace copied from supervisor_workspace_template
; during cold start.  A module descriptor contains three dictionary lists:
;
;   descriptor +0   exported names
;   descriptor +3   LIST -> second six-byte pair
;   second pair +0  imported names
;   second pair +3  local names owned by the module
;
; The root module keeps its second pair directly in this workspace, so its
; import and local dictionaries are also permanent garbage-collector roots.
; Miniature module example
; ------------------------
; Suppose module M exports E, imports I, and privately owns L:
;
;       MODULE_CURRENT_CELL -> constant M
;       M.value             -> MODULE descriptor
;                                +0 exports -> (E)
;                                +3 pair
;                                    +0 imports -> (I)
;                                    +3 locals  -> (L)
;
; A lookup made while M is open searches system names first, then E, then I,
; then L.  Exported and imported dictionary nodes preserve canonical value-cell
; identity; the lists describe visibility, not copies of the constants.
MODULE_CURRENT_CELL:                equ 09a8dh ; CONST(current module object)
MODULE_CURRENT_OBJECT:              equ 09a8eh ; payload of MODULE_CURRENT_CELL
MODULE_CURRENT_DESCRIPTOR:          equ 09a91h ; payload of current module object
MODULE_CURRENT_PROGRAM:                equ MODULE_CURRENT_DESCRIPTOR ; legacy alias
ROOT_MODULE_IMPORT_DICTIONARY:      equ 09a93h
ROOT_MODULE_LOCAL_DICTIONARY:       equ 09a96h
GC_DICTIONARY_ROOT_A:               equ ROOT_MODULE_IMPORT_DICTIONARY ; legacy alias
GC_DICTIONARY_ROOT_B:               equ ROOT_MODULE_LOCAL_DICTIONARY  ; legacy alias
MODULE_ROOT_IMPORT_CELL_PTR:        equ 09a89h ; temporary pointer used by CRMOD/KILL
MODULE_ROOT_LOCAL_CELL_PTR:         equ 09a8bh ; temporary pointer used by CRMOD/KILL
GC_ERROR_HANDLER_ROOT:              equ 09b19h

MODULE_DESCRIPTOR_EXPORTS:          equ 000h
MODULE_DESCRIPTOR_SECOND_PAIR:      equ 003h
MODULE_SECOND_PAIR_IMPORTS:         equ 000h
MODULE_SECOND_PAIR_LOCALS:          equ 003h

; Dictionary names occupy a separately managed pool.  One bitmap bit represents
; one eight-byte pool block.  The first block holds the three-byte value cell,
; up to four name bytes and the 0xFF terminator; each additional block adds eight
; name bytes.  Input names use 0xFE as the temporary terminator.
; ----------------------------------------------------------------------------
; MEMORY GROWS FROM BOTH ENDS
; ----------------------------------------------------------------------------
;
; The fixed workspace is followed by the dictionary-name pool and then by one
; shared arena.  Execution frames and fresh clause variables grow upward.
; Managed term objects grow downward.  Allocation succeeds while the two
; frontiers remain apart; when they approach, the collector marks live objects,
; trims dead objects from the heap edge, and threads interior holes into a free
; list.
;
; Dictionary spellings use a separate bitmap allocator because their addresses
; must remain stable: compiled constants point at canonical dictionary value
; cells, not at copies of their text.
;
DICTIONARY_NAME_POOL_BASE_PTR:       equ 09805h
DICTIONARY_ALLOCATION_BITMAP:       equ 09a99h
DICTIONARY_INPUT_BUFFER:            equ 09ca5h
DICTIONARY_INPUT_GUARD:             equ 09ce4h
DICTIONARY_INPUT_TERMINATOR:        equ 0feh
DICTIONARY_STORED_TERMINATOR:       equ 0ffh
DICTIONARY_DYNAMIC_VALUE_MIN:        equ DICTIONARY_NAME_POOL_START ; first user-name value cell
; With the stock 48K top-of-memory stack, cold start reserves 0x1180 bytes for
; dictionary names (560 eight-byte blocks) and initializes 70 bitmap bytes.
; The calculation is dynamic, so these values document the distributed image
; rather than imposing constants on relocated builds.
DEFAULT_DICTIONARY_POOL_BYTES:          equ 01180h
DEFAULT_DICTIONARY_POOL_BLOCKS:         equ 0230h
DEFAULT_DICTIONARY_BITMAP_BYTES:        equ 046h
DEFAULT_EXEC_ARENA_LIMIT:               equ 0af25h
DICTIONARY_POOL_BLOCK_SIZE:         equ 008h
DICTIONARY_FIRST_BLOCK_NAME_BYTES:  equ 004h
DICTIONARY_EXTRA_BLOCK_NAME_BYTES:  equ 008h

; Relation-database scratch.  ADDCL uses these words while it transforms a
; caller-owned clause term into the persistent compiled representation and
; splices the resulting node into the selected relation list.
DATABASE_NEW_CLAUSE_PAIR:             equ 09a85h
DATABASE_RELATION_VALUE_CELL:          equ 09a87h
ADDCL_APPEND_POSITION:                 equ 07fffh ; any larger request appends

; Fresh-variable map shared by the generic term copier and ADDCL compiler.
; Entries are source-variable addresses.  The high byte 0xFF in the next slot
; terminates the table; the entry ordinal multiplied by three is the relative
; local-environment offset stored in compiled clauses.
FRESH_VARIABLE_SOURCE_MAP:             equ 0986fh
FRESH_VARIABLE_MAP_END_HIGH:           equ FRESH_VARIABLE_SOURCE_MAP+1

; -----------------------------------------------------------------------------
; Central execution state and 12-byte continuation/choice records
; -----------------------------------------------------------------------------
; The interpreter keeps the hot execution registers in fixed workspace words.
; Selecting a user clause copies these six words, in order, into a 12-byte
; record after the clause's local-variable cells.  The record is both a return
; continuation and, when another clause remains, a backtracking choice point.
;
; The field names below are supported by allocation, normal return, cut, and
; rollback paths.  EXEC_ALLOCATION_TOP is the next free byte while the matching
; frame field records the base of the selected clause's local environment.
EXEC_FRAME_TOP:                 equ 0983dh
EXEC_ROOT_FRAME:                equ 0983fh
; ----------------------------------------------------------------------------
; THE SIX HOT WORDS
; ----------------------------------------------------------------------------
;
; These addresses are the micro-PROLOG equivalent of a processor register set.
; The inner interpreter keeps the current clause cursor, frame, goal stream,
; choice point, trail head and allocation frontier here because fixed-address
; loads are cheaper than repeatedly indexing a larger structure.
;
; Selecting a clause snapshots all six words into a frame.  Backtracking
; restores all six in one LDIR.  That symmetry is the central control-flow
; trick of the system: failure is not a collection of special cases, but a
; restoration of an earlier virtual-machine state.
;
; ----------------------------------------------------------------------------
; TRANSITIONS OF THE SIX HOT LOGICAL WORDS
; ----------------------------------------------------------------------------
;
;   event             fields which principally change
;   ----------------  -------------------------------------------------------
;   call entry         NEXT_CLAUSE and LOCAL_BASE describe the selected call;
;                      CALLER, caller GOALS, PREVIOUS_CHOICE and SAVED_TRAIL
;                      preserve the continuation in the new frame
;   goal success       CURRENT_GOALS advances to its tail; frame is unchanged
;   clause failure     all six words are restored from the newest choice frame
;                      and NEXT_CLAUSE becomes the retry relation-list suffix
;   normal return      caller frame and caller remaining goals are restored;
;                      execution/local frontier is rewound to the caller
;
; These words act like the registers of the Prolog virtual machine.  A frame is
; a frozen copy from which failure or return can reconstruct a prior state.
EXEC_NEXT_CLAUSE:                equ 09841h
EXEC_CURRENT_FRAME:              equ 09843h
EXEC_CURRENT_GOALS:              equ 09845h
EXEC_CHOICE_FRAME:               equ 09847h
EXEC_TRAIL_HEAD:                 equ 09849h
EXEC_ALLOCATION_TOP:             equ 0984bh

; Scratch values describing the clause currently being attempted.
EXEC_SELECTED_BODY:              equ 0984dh
EXEC_CALL_ARGUMENTS:             equ 0984fh
EXEC_SELECTED_HEAD:              equ 09851h
EXEC_CALLER_ENV_BASE:            equ 09853h
EXEC_CLAUSE_ENV_BASE:            equ 09855h
EXEC_PREVIOUS_FRAME_TOP:         equ 09857h
EXEC_RELOCATION_DELTA:           equ 09859h

; Managed-term allocation state.  Six-byte heap objects are allocated downward
; from TERM_HEAP_CURSOR.  FREE_TERM_OBJECT_HEAD links reusable two-cell objects;
; TERM_HEAP_COLLECTION_TRIGGER is the adaptive address that triggers collection
; before another downward allocation.  EXEC_ARENA_ORIGIN is the fixed high heap
; boundary used by collector address classification.
EXEC_ARENA_ORIGIN:                equ 09839h
TERM_HEAP_CURSOR:                 equ 0983bh
FREE_TERM_OBJECT_HEAD:            equ 0985bh
TERM_HEAP_COLLECTION_TRIGGER:     equ 0985dh
TERM_HEAP_FREE_BYTES:             equ 0985fh
TERM_HEAP_FREE_BYTES_HIGH:        equ TERM_HEAP_FREE_BYTES+1

; Every user-relation call receives a frame because every call needs a
; continuation.  A frame becomes a *choice point* only when the selected clause
; has a following clause: then EXEC_CHOICE_FRAME is made to point at that frame.
; A last-clause call still has a frame, but leaves the older choice point visible.
EXEC_FRAME_SIZE:                equ 00ch
; ----------------------------------------------------------------------------
; EXECUTION FRAMES: CONTINUATION AND CHOICE POINT IN ONE RECORD
; ----------------------------------------------------------------------------
;
; A selected user clause receives one twelve-byte frame.  The same record does
; two jobs.  It remembers where successful execution returns, and—when another
; clause remains—it remembers enough state to retry after failure.
;
; The six hot words at EXEC_NEXT_CLAUSE are copied into this layout when a frame
; is built and copied back when a choice point is restored.  This literal block
; copy is why the field order matters so much: it is an on-disk-style ABI inside
; the interpreter itself.
;
; Logical caller order and physical frame order are not identical.  Normal
; return follows EXEC_FRAME_CALLER.  Garbage collection walks physically
; allocated frames, including suspended choice points.  Tail-call relocation
; can change physical placement while preserving the logical links.
;
EXEC_FRAME_NEXT_CLAUSE:         equ 000h
EXEC_FRAME_CALLER:              equ 002h
EXEC_FRAME_CALLER_GOALS:        equ 004h
EXEC_FRAME_PREVIOUS_CHOICE:     equ 006h
EXEC_FRAME_SAVED_TRAIL:         equ 008h
EXEC_FRAME_LOCAL_BASE:          equ 00ah

