deftrap-mod("?ERROR?")(q c is-told add if tell data-rel)
((respond q X)
  (ABORT))
((respond tell (X|Y))
  /
  (add (X Z if (X Z) is-told))
  (X|Y))
((respond c X)
  /
  X)
((respond / X)
  /
  (R Y)
  (R Z)
  (Y Z)
  (P "error&")
  (R x)
  /
  (respond x X))
((respond X (Y|Z))
  (PP to quit enter : q)
  (PP or enter : tell (see manual))
  (P or enter : / "<any command>" (eg / add (sentence) , / load file))
  (PP)
  (PP to continue enter : c)
  (P "error&")
  (R x)
  (respond x (Y|Z)))
((E-code 6 "CLOSE last used file first"))
((E-code 15 "Break ! during tape read or write"))
((P-code 0 "Arithmetic overflow"))
((P-code 1 "Arithmetic underflow"))
((P-code 3 "Too many variables"))
((P-code 5 "File error"))
((P-code 9 "Write error"))
((P-code 11 "Break !"))
((P-code 12 "Illegal use of modules"))
((P-code 13 "Line or point off screen"))
((P-code 22 "Illegal colour"))
((P-code X " "))
((COPYRIGHT 1983 LPA LTD (V 6 -15)))
(("?ERROR?" 4 (ADDCL ((X|Y)|Z)|x))
  (P "Cannot add sentences to" X)
  (PP)
  ABORT)
(("?ERROR?" 2 (X|Y))
  (CL ((data-rel X)))
  /
  FAIL)
(("?ERROR?" 2 (X|Y))
  /
  (PP No definition for X)
  (PP trying : X Y)
  (P "error&(? for info)")
  (R Z)
  (respond Z (X|Y)))
(("?ERROR?" X (Y|Z))
  (P-code X x)
  (P Evaluation error X : x)
  (PP)
  (PP trying : Y Z)
  ABORT)
CLMOD
