simshow-mod(show draw)("FIND:" : picture ON Parse-of-ConjC)
((showex X Y)
  (? Y)
  (PP|X)
  (FORALL ((ON Z X)) ((draw Z)))
  FAIL)
((showex X Y))
((show X)
  ("FIND:" X Y Z show)
  (Parse-of-ConjC (:) x Z)
  (showex Y x))
((draw X)
  (VAR X)
  /
  FAIL)
((draw X)
  (picture X)
  /)
((draw (X|Y))
  (FORALL ((ON Z (X|Y))) ((draw Z))))
CLMOD
