spytrace-mod(spy unspy spying)(spypoints on off)
((APPEND () X X)
  /)
((APPEND (X|Y) Z (X|x))
  (APPEND Y Z x))
((upgoal X)
  (DELCL ((goal X)))
  (SUM X 1 Y)
  (ADDCL ((goal Y))))
((reset X)
  (DELCL ((goal Y)))
  (ADDCL ((goal X))))
((goal 0))
((COPYRIGHT 1983 LPA LTD (V 13 -4)))
((spy X)
  (CON X)
  (ADDCL ((X|Y) (spypoints on) (/) (spying X Y)) 0))
((unspy X)
  (CON X)
  (DELCL ((X|Y) (spypoints on) (/) (spying X Y))))
((spying on)
  (KILL spypoints)
  (ADDCL ((spypoints on))))
((spying off)
  (KILL spypoints)
  (ADDCL ((spypoints off))))
((spying X Y)
  (upgoal Z)
  (OR ((PP Z : X Y)) ((PP Z backtracking on X Y) (reset Z) FAIL))
  (CL ((X|Y)|x) 1 y)
  (NOT EQ x ((spypoints on) (/)|z))
  (PP Z matches sentence y)
  (APPEND x ((PP Z solved : X Y)) X1)|X1)
CLMOD
